### PR TITLE
Removed uneeded LINUX conditional around LSLFload operators  It causes e...

### PR DESCRIPTION
**Pull request by mdickson**
Compilation fix for Linux/Mono.  Also a commit to handle byte ranges on texture fetches used by the newer viewers.

### CODE REVIEW

**Comment by fly-man-** [comment]
Have looked throught this code and doesn't look like it breaks anything at the moment

**Comment by mdickson** [comment]
Which one?  There are 2 commits there.  The conditional compile broke a mono 3.2 compile.  The operator was used and missing.   The texture fetching change is missing functionality.  The newer viewers will use this new syntax.

**Comment by fly-man-** [comment]
Both commits are good to be pulled into the master. However, there's only 2 people that can pull these into the repo.

PS: Have a look at https://github.com/greythane/Aurora-Sim for some commits that you might want to apply to your own tree

**Comment by greythane** [comment]
I use Linux and Mac with mono V 3.2. I found that some of the conditional and commented out code for lsl operations caused errors in even simple scripts..  
There are two as I initially patched one problematic set and later found a few more.

**Pull request merged**
