### PR TITLE
Embedded Rico's configurator in Base

### PR DESCRIPTION
**Pull request by JAllard**
Moved Aurora.Configurator in Base - Added run configurator console command. Aurora and/or AuroraServer automatically check if this is your first run. If so it runs old Ricos configurator (embedded) or just skip it if you say no (default). Everytime you need to configure your Aurora again just use the console command -run configurator- and it reloads configs at the end

### CODE REVIEW

**Comment by RevolutionSmythe** [comment]
I have an issue with this pull request... the whole region his project is in an .exe is because it sets up Aurora, so it is supposed to run before Aurora.exe (and Aurora.Server.exe) are ever run. If this is merged in, you can only setup Aurora once you have already started it, which doesn't mean sense to me. The other two commits about fixing osAvatarStopAnimation and removing warnings though, we can merge those in.

**Comment by JAllard** [comment]
Since Aurora and AuroraServer run the same BaseApplication, it is possible to configure them soon after they did their own migration (it does service.MigrateBin(); then Configure();). The method then checks the Process.GetCurrentProcess(); and runs the proper .ini configurations. That is "before" they are ever run. Also, adding the run configurator console command, allows you to quickly and easily reconfigure your region/server without having to stop the instance (once i'll implement the HandleConfigRefresh in BaseApplication though, right now it is in SimulationBase). Say like you have a window application and when you start it, it checks if it is configured itself : you dont have to go around to find the configurator e.g. when you first run Microsoft Office (or the most of the other applications). Btw, please let me know if you really wont merge this, so i can revert it in my repo too,  mantaining a synchronized one with the official project. Thanks !

**Comment by RevolutionSmythe** [comment]
Ok, sorry, I misread the commit, it actually looks great then. There's a couple of things that ought to be cleaned up, like the Process.ToString() (https://github.com/JAllard/Aurora-Sim/commit/5121a04cd0e65802bd4b2b3871704b3d460cb4fc#L1R229) and that MainConsole.Instance shouldn't be force initialized, but instead, the configuration probably should come right after the console is set up (especially, when I don't notice immediately anything using MainConsole.Instance, in which case, you can just remove the initialization).

**Comment by JAllard** [comment]
Done ! Tx !

**Pull request merged**
