### PR TITLE
Schema definition

### PR DESCRIPTION
**Pull request by SignpostMarv**
It always bugged me that a general-purpose structure was used for schema definitions. Added and implemented a specific class for defining schemas.

### CODE REVIEW

**Comment by skidzTweak** [comment]
I like that... does make them a little more strait forward... 
You test this on new regions and sqlite?

**Comment by SignpostMarv** [comment]
Seems to behave identically compared to master- there's a bunch of spew that crops up under sqlite on both branches.

**Comment by RevolutionSmythe** [comment]
Looks great to me, if there aren't any issues, I'm fine with this being merged in.

**Comment by SignpostMarv** [comment]
I was chatting with the opensim devs and it seems that the stuff that aurora-sim isn't currently using (priority queue in in the image manager) is of uncertain utility- e.g. the developer who implemented it isn't around and people aren't 100% certain what it does.

So it's possible that the C5 lib could be removed entirely, but it depends on whether a replacement first-party priority queuer is more efficient than the stuff that's been there since 2009.

**Comment by RevolutionSmythe** [comment]
Yeah, I know. I had considered removing it previously, and redoing the image manager, however, the image manager is pretty much deprecated already, as HTTP textures are used in most viewers now. The current C5 code in the Image Manager is terrible anyways, as it ends up causing random errors over time, even when locks are properly applied.

**Pull request merged**
