### PR TITLE
Broken compilation for VS2008

### PR DESCRIPTION
**Pull request by fly-man-**
The change triggered in 44b87626bafcd07ff6458cfe2e5dd02a906e6740 has broken compilation in VS2008.

Small change but strange that it doesn't work properly

### CODE REVIEW

**Comment by RevolutionSmythe** [comment]
This isn't right, as the code that you submitted will always set lineStart to the default value. It needs to check whether it's blank or null before doing that.

**Comment by fly-man-** [comment]
Then how can this be fixed so the compilation on VS2008 machines doesn't trigger an build error ?

**Comment by RevolutionSmythe** [comment]
Add the line 
if (string.IsNullOrEmpty(lineStart))

before 
lineStart = "\t";

The way that you did it always forces lineStart to be "\t", when it should only be that if a value is not specified (aka it's null).

**Comment by fly-man-** [comment]
Change was applied to the commit, if someone is able to check them

**Pull request merged**
