### PR TITLE
Attempt to port osGetGatekeeperURI from opensim

### PR DESCRIPTION
**Pull request by JAllard**
we really shoudnt use this...

### CODE REVIEW

**Comment by JAllard** [comment]
@Fly-Man : ported the whole list you gave in IRC except osSetStateEvents which was an old and now unused debugging functions and osTeleportOwner which already is in.

**Comment by JAllard** [comment]
Sorry Fly-Man we should find a better way for osSaveAppearance. Reverted.

**Comment by RevolutionSmythe** [comment]
This is a collection of commits that don't merge in anymore, could we possibly have it merged into one commit without a couple of reverts in there? Thanks!

**Comment by JAllard** [comment]
sure thing !

**Pull request closed without merging**
